version: 2.1

orbs:
  docker-buildx: foodles/docker-buildx@0.0.1

workflows:
  version: 2
  build-and-publish-docker-image:
    jobs:
      - docker-buildx/publish:
          name: build_deploy_docker_dev
          context: docker-publishing
          checkout: true
          attach-workspace: true
          image: foodlestech/r7insight_docker
          tag: develop
          filters:
            branches:
              only:
                - develop